### ISSUE TITLE
EXCEPTION: Kmer solidity has more thresholds (1) than banks (0)

### ISSUE THREAD

**Issue by KartikaFauzia** [johnlees/unitig-counter#12]
Hi, 
I run unitig-counter on 50 assemblies of H. pylori genome (.fna). I installed unitig-counter by conda. 

unitig-counter -strains allasia_list.txt -output output -nb-cores 4

But I could not get results and always get this comment:

EXCEPTION: Kmer solidity has more thresholds (1) than banks (0)

Do you have any suggestions? What did i do wrong? 

Thank you so much for your help

**Comment by johnlees** [comment]
What does your file allasia_list.txt look like?

**Comment by KartikaFauzia** [comment]
Here is my list look like:

[allasia_list.txt](https://github.com/johnlees/unitig-counter/files/6581495/allasia_list.txt)

**Comment by johnlees** [comment]
This looks ok to me, so I think this must be an issue raised by GATB. I couldn't find anything on their issues documenting this, so you could ask there.

Alternatively, you could try this package: https://github.com/johnlees/unitig-caller

**Comment by rchikhi** [comment]
It does look good to me too. I wonder if the problem occurs again on test data, or if unitig-counter provides no test data then on a smaller list of banks (e.g. just the first 3 lines just to see). Otherwise indeed it seem unitig-caller is the next-generation tool to try :)

**Comment by johnlees** [comment]
It might also be worth checking that all of those files can be found, and that they all contain sequence.

**Comment by rchikhi** [comment]
yep indeed. Also it seems that usable test data is here: https://github.com/johnlees/unitig-caller/blob/master/test/simple_refs.txt

**Comment by KartikaFauzia** [comment]
Thank you very much for your replies, I actually tried using the dataset example from https://github.com/johnlees/unitig-caller/blob/master/test/simple_refs.txt and it works fine.  
Some of my sequence input files seem to have some errors (typo at the beginning of header). 
It works after correcting it.
