### ISSUE TITLE
output files: unitigs.unique_rows_to_all_rows.txt

### ISSUE THREAD

**Issue by luciagrami** [johnlees/unitig-counter#13]
Hello,

I need  help in understanding what is the information contained in  the unitigs.unique_rows_to_all_rows.txt file.
I thought it was a list of unitigs with identical patterns, but for example if I take a row:

8 = 12558, 122547, etc

both 8 and 12558 can be found in the file unitigs.unique_rows.Rtab and also their presence-absence pattern is not identical.

Thanks!
L.

**Comment by johnlees** [comment]
This means that row index 8 in unitigs.unique_rows.Rtab corresponds to rows 12558 and 122547 in the unitigs and nodes files, which list the actual sequences which have this pattern

**Comment by luciagrami** [comment]
Thanks !
