### ISSUE TITLE
Please add Boost as ExternalProject

### ISSUE THREAD

**Issue by leoisl** [johnlees/unitig-counter#3]
Hello!

Thanks for this repo!

I tried to compile, got this error:
```
CMake Error at /usr/share/cmake-3.13/Modules/FindBoost.cmake:2100 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.62.0

  Boost include path: /usr/include

  Detected version of Boost is too old.  Requested version was 1.69 (or
  newer).
Call Stack (most recent call first):
  CMakeLists.txt:71 (FIND_PACKAGE)
```

This is a clean way to do it (there should be several examples around, sorry if you already have a template): https://github.com/iqbal-lab-org/gramtools/blob/master/libgramtools/lib/boost.cmake . Just in case, don't get DBGWAS example as template (I don't know why I tried the BoostSuperBuild approach, it is a mess now... Will update the build script some time...). If you know a better one, please let me know!

Thanks!

**Comment by johnlees** [comment]
The CMake in here is the DBGWAS example, with some edits and bits cut out, so I'm sure it's ended up as a bit of a mess!

My preferred way to install is just via conda:
```
conda install -c bioconda unitig-counter
```

But if you want to compile from source to make changes I can address this too. Were you following the instructions in `INSTALL.md`?

**Comment by leoisl** [comment]
Hello again!

Sorry about this issue, conda works perfectly, no need to compile from the source, I'd say...

Thanks for the quick answer!
Closing!

**Comment by johnlees** [comment]
I realise I don't have that option in the README, I will add it now!
